[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
chrono = "0.4"
actix-web = "4.4"
actix-rt = "2.9"
env_logger = "0.10"
log = "0.4"
